### PR TITLE
Minor changes on our end + one new option

### PR DESCRIPTION
**Pull request by DingoEatingFuzz**
This is a migration of https://github.com/segmentio/analytics.js-integrations/pull/634

It is dependent on: https://github.com/segmentio/facade/pull/76

And there is still this outstanding question: How do I go about getting the new stream option added under the advanced options section on the Segment site?

### CODE REVIEW

**Comment by f2prateek** [comment]
@DingoEatingFuzz could you describe what the new 'stream' option is? e.g. here's what we have for the existing options: (we'd need at least a description, label and type)

``` js
"apiKey": {
      "default": "",
      "description": "Your API key should be a series of numbers and letters, like `3daDLlqb4ANg7l0rf4cfl6xF`.",
      "label": "API Key",
      "type": "string",
      "validators": [
        [
          "regexp",
          "^\\w{10,30}$",
          "Double-check your API Key. It should be a series of numbers and letters, like `3daDLlqb4ANg7l0rf4cfl6xF`."
        ]
      ]
    },
    "cid": {
      "default": "",
      "description": "Your CID should be a series of numbers, like `9289`.",
      "label": "CID",
      "type": "string",
      "validators": [
        [
          "required",
          "Please enter your Lytics CID."
        ],
        [
          "regexp",
          "^\\d+$",
          "Double-check your CID. It should be a series of numbers, like `9289`."
        ]
      ]
    }
```

**Comment by DingoEatingFuzz** [comment]
@f2prateek how does this look?

``` json
"stream": {
  "default": "default",
  "description": "A brief, but informative name for organizating your data in Lytics. Only necessary when you are tracking multiple websites.",
  "label": "Stream",
  "type": "string",
  "validators": [
    [
      "regexp",
      "^[-_\\w]{3,50}$",
      "Double-check your stream. It must be alpha-numeric with no spaces (hyphens and underscores are fine)."
    ]
  ]
}
```

**Comment by f2prateek** [comment]
Thanks!

**Comment by f2prateek** [comment]
@DingoEatingFuzz sorry jumped the gun on this, mind reopening the PR?

**Comment by f2prateek** [comment]
Todos (for Segment):
- [ ] https://github.com/segmentio/facade/pull/76
- [ ] Update Metadata (provided in this conversation
- [ ] Merge PR
- [ ] Deploy

**Comment by DingoEatingFuzz** [comment]
@f2prateek There is no option to reopen a PR, but I opened #3, which has the same diff.

**Pull request merged**
